name: Code Coverage

on:
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test API
        run: |
          cd api
          npm install
          npm test
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} npm run push-report
      - name: Test Backend
        run: |
          cd backend
          npm install
          npm test
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} npm run push-report
        env:
          CI: true
